"""empty message

Revision ID: 254052792c20
Revises: 622e4ed44e00
Create Date: 2023-12-05 11:35:06.571517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254052792c20'
down_revision = '622e4ed44e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('ac')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ac', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
