"""empty message

Revision ID: 5801e6e3dff9
Revises: 850f0bc1c1b9
Create Date: 2023-12-03 16:30:59.725508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5801e6e3dff9'
down_revision = '850f0bc1c1b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('hit_die', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_class_name'), ['name'], unique=False)

    op.create_table('player_race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_race', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_race_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_race', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_race_name'))

    op.drop_table('player_race')
    with op.batch_alter_table('player_class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_class_name'))

    op.drop_table('player_class')
    # ### end Alembic commands ###
