"""empty message

Revision ID: da08ad9adbcc
Revises: 
Create Date: 2023-12-03 16:09:53.837207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da08ad9adbcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('str', sa.Integer(), nullable=True),
    sa.Column('dex', sa.Integer(), nullable=True),
    sa.Column('con', sa.Integer(), nullable=True),
    sa.Column('int', sa.Integer(), nullable=True),
    sa.Column('wis', sa.Integer(), nullable=True),
    sa.Column('cha', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('ac', sa.Integer(), nullable=True),
    sa.Column('spd', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('hp_max', sa.Integer(), nullable=True),
    sa.Column('insp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_name'))

    op.drop_table('player')
    # ### end Alembic commands ###
